// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pc2d.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_pc2d_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_pc2d_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_pc2d_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_pc2d_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_pc2d_2eproto;
class MySuperStruct;
struct MySuperStructDefaultTypeInternal;
extern MySuperStructDefaultTypeInternal _MySuperStruct_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::MySuperStruct* Arena::CreateMaybeMessage<::MySuperStruct>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class MySuperStruct final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MySuperStruct) */ {
 public:
  inline MySuperStruct() : MySuperStruct(nullptr) {}
  ~MySuperStruct() override;
  explicit PROTOBUF_CONSTEXPR MySuperStruct(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MySuperStruct(const MySuperStruct& from);
  MySuperStruct(MySuperStruct&& from) noexcept
    : MySuperStruct() {
    *this = ::std::move(from);
  }

  inline MySuperStruct& operator=(const MySuperStruct& from) {
    CopyFrom(from);
    return *this;
  }
  inline MySuperStruct& operator=(MySuperStruct&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MySuperStruct& default_instance() {
    return *internal_default_instance();
  }
  static inline const MySuperStruct* internal_default_instance() {
    return reinterpret_cast<const MySuperStruct*>(
               &_MySuperStruct_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MySuperStruct& a, MySuperStruct& b) {
    a.Swap(&b);
  }
  inline void Swap(MySuperStruct* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MySuperStruct* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MySuperStruct* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MySuperStruct>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MySuperStruct& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MySuperStruct& from) {
    MySuperStruct::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MySuperStruct* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MySuperStruct";
  }
  protected:
  explicit MySuperStruct(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuperStringFieldNumber = 1,
    kSuperIntFieldNumber = 2,
    kSuperFloatFieldNumber = 3,
  };
  // string superString = 1;
  void clear_superstring();
  const std::string& superstring() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_superstring(ArgT0&& arg0, ArgT... args);
  std::string* mutable_superstring();
  PROTOBUF_NODISCARD std::string* release_superstring();
  void set_allocated_superstring(std::string* superstring);
  private:
  const std::string& _internal_superstring() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_superstring(const std::string& value);
  std::string* _internal_mutable_superstring();
  public:

  // int32 superInt = 2;
  void clear_superint();
  int32_t superint() const;
  void set_superint(int32_t value);
  private:
  int32_t _internal_superint() const;
  void _internal_set_superint(int32_t value);
  public:

  // float superFloat = 3;
  void clear_superfloat();
  float superfloat() const;
  void set_superfloat(float value);
  private:
  float _internal_superfloat() const;
  void _internal_set_superfloat(float value);
  public:

  // @@protoc_insertion_point(class_scope:MySuperStruct)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr superstring_;
    int32_t superint_;
    float superfloat_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_pc2d_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MySuperStruct

// string superString = 1;
inline void MySuperStruct::clear_superstring() {
  _impl_.superstring_.ClearToEmpty();
}
inline const std::string& MySuperStruct::superstring() const {
  // @@protoc_insertion_point(field_get:MySuperStruct.superString)
  return _internal_superstring();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MySuperStruct::set_superstring(ArgT0&& arg0, ArgT... args) {
 
 _impl_.superstring_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:MySuperStruct.superString)
}
inline std::string* MySuperStruct::mutable_superstring() {
  std::string* _s = _internal_mutable_superstring();
  // @@protoc_insertion_point(field_mutable:MySuperStruct.superString)
  return _s;
}
inline const std::string& MySuperStruct::_internal_superstring() const {
  return _impl_.superstring_.Get();
}
inline void MySuperStruct::_internal_set_superstring(const std::string& value) {
  
  _impl_.superstring_.Set(value, GetArenaForAllocation());
}
inline std::string* MySuperStruct::_internal_mutable_superstring() {
  
  return _impl_.superstring_.Mutable(GetArenaForAllocation());
}
inline std::string* MySuperStruct::release_superstring() {
  // @@protoc_insertion_point(field_release:MySuperStruct.superString)
  return _impl_.superstring_.Release();
}
inline void MySuperStruct::set_allocated_superstring(std::string* superstring) {
  if (superstring != nullptr) {
    
  } else {
    
  }
  _impl_.superstring_.SetAllocated(superstring, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.superstring_.IsDefault()) {
    _impl_.superstring_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:MySuperStruct.superString)
}

// int32 superInt = 2;
inline void MySuperStruct::clear_superint() {
  _impl_.superint_ = 0;
}
inline int32_t MySuperStruct::_internal_superint() const {
  return _impl_.superint_;
}
inline int32_t MySuperStruct::superint() const {
  // @@protoc_insertion_point(field_get:MySuperStruct.superInt)
  return _internal_superint();
}
inline void MySuperStruct::_internal_set_superint(int32_t value) {
  
  _impl_.superint_ = value;
}
inline void MySuperStruct::set_superint(int32_t value) {
  _internal_set_superint(value);
  // @@protoc_insertion_point(field_set:MySuperStruct.superInt)
}

// float superFloat = 3;
inline void MySuperStruct::clear_superfloat() {
  _impl_.superfloat_ = 0;
}
inline float MySuperStruct::_internal_superfloat() const {
  return _impl_.superfloat_;
}
inline float MySuperStruct::superfloat() const {
  // @@protoc_insertion_point(field_get:MySuperStruct.superFloat)
  return _internal_superfloat();
}
inline void MySuperStruct::_internal_set_superfloat(float value) {
  
  _impl_.superfloat_ = value;
}
inline void MySuperStruct::set_superfloat(float value) {
  _internal_set_superfloat(value);
  // @@protoc_insertion_point(field_set:MySuperStruct.superFloat)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_pc2d_2eproto
