// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pc2d.proto

#include "pc2d.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR MySuperStruct::MySuperStruct(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.superstring_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.superint_)*/0
  , /*decltype(_impl_.superfloat_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MySuperStructDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MySuperStructDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MySuperStructDefaultTypeInternal() {}
  union {
    MySuperStruct _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MySuperStructDefaultTypeInternal _MySuperStruct_default_instance_;
static ::_pb::Metadata file_level_metadata_pc2d_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_pc2d_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_pc2d_2eproto = nullptr;

const uint32_t TableStruct_pc2d_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MySuperStruct, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::MySuperStruct, _impl_.superstring_),
  PROTOBUF_FIELD_OFFSET(::MySuperStruct, _impl_.superint_),
  PROTOBUF_FIELD_OFFSET(::MySuperStruct, _impl_.superfloat_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::MySuperStruct)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_MySuperStruct_default_instance_._instance,
};

const char descriptor_table_protodef_pc2d_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\npc2d.proto\"J\n\rMySuperStruct\022\023\n\013superSt"
  "ring\030\001 \001(\t\022\020\n\010superInt\030\002 \001(\005\022\022\n\nsuperFlo"
  "at\030\003 \001(\002b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_pc2d_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_pc2d_2eproto = {
    false, false, 96, descriptor_table_protodef_pc2d_2eproto,
    "pc2d.proto",
    &descriptor_table_pc2d_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_pc2d_2eproto::offsets,
    file_level_metadata_pc2d_2eproto, file_level_enum_descriptors_pc2d_2eproto,
    file_level_service_descriptors_pc2d_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_pc2d_2eproto_getter() {
  return &descriptor_table_pc2d_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_pc2d_2eproto(&descriptor_table_pc2d_2eproto);

// ===================================================================

class MySuperStruct::_Internal {
 public:
};

MySuperStruct::MySuperStruct(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:MySuperStruct)
}
MySuperStruct::MySuperStruct(const MySuperStruct& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MySuperStruct* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.superstring_){}
    , decltype(_impl_.superint_){}
    , decltype(_impl_.superfloat_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.superstring_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.superstring_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_superstring().empty()) {
    _this->_impl_.superstring_.Set(from._internal_superstring(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.superint_, &from._impl_.superint_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.superfloat_) -
    reinterpret_cast<char*>(&_impl_.superint_)) + sizeof(_impl_.superfloat_));
  // @@protoc_insertion_point(copy_constructor:MySuperStruct)
}

inline void MySuperStruct::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.superstring_){}
    , decltype(_impl_.superint_){0}
    , decltype(_impl_.superfloat_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.superstring_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.superstring_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

MySuperStruct::~MySuperStruct() {
  // @@protoc_insertion_point(destructor:MySuperStruct)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MySuperStruct::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.superstring_.Destroy();
}

void MySuperStruct::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MySuperStruct::Clear() {
// @@protoc_insertion_point(message_clear_start:MySuperStruct)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.superstring_.ClearToEmpty();
  ::memset(&_impl_.superint_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.superfloat_) -
      reinterpret_cast<char*>(&_impl_.superint_)) + sizeof(_impl_.superfloat_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MySuperStruct::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string superString = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_superstring();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "MySuperStruct.superString"));
        } else
          goto handle_unusual;
        continue;
      // int32 superInt = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.superint_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float superFloat = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 29)) {
          _impl_.superfloat_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MySuperStruct::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MySuperStruct)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string superString = 1;
  if (!this->_internal_superstring().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_superstring().data(), static_cast<int>(this->_internal_superstring().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "MySuperStruct.superString");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_superstring(), target);
  }

  // int32 superInt = 2;
  if (this->_internal_superint() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_superint(), target);
  }

  // float superFloat = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_superfloat = this->_internal_superfloat();
  uint32_t raw_superfloat;
  memcpy(&raw_superfloat, &tmp_superfloat, sizeof(tmp_superfloat));
  if (raw_superfloat != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(3, this->_internal_superfloat(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MySuperStruct)
  return target;
}

size_t MySuperStruct::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MySuperStruct)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string superString = 1;
  if (!this->_internal_superstring().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_superstring());
  }

  // int32 superInt = 2;
  if (this->_internal_superint() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_superint());
  }

  // float superFloat = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_superfloat = this->_internal_superfloat();
  uint32_t raw_superfloat;
  memcpy(&raw_superfloat, &tmp_superfloat, sizeof(tmp_superfloat));
  if (raw_superfloat != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MySuperStruct::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MySuperStruct::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MySuperStruct::GetClassData() const { return &_class_data_; }


void MySuperStruct::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MySuperStruct*>(&to_msg);
  auto& from = static_cast<const MySuperStruct&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MySuperStruct)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_superstring().empty()) {
    _this->_internal_set_superstring(from._internal_superstring());
  }
  if (from._internal_superint() != 0) {
    _this->_internal_set_superint(from._internal_superint());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_superfloat = from._internal_superfloat();
  uint32_t raw_superfloat;
  memcpy(&raw_superfloat, &tmp_superfloat, sizeof(tmp_superfloat));
  if (raw_superfloat != 0) {
    _this->_internal_set_superfloat(from._internal_superfloat());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MySuperStruct::CopyFrom(const MySuperStruct& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MySuperStruct)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MySuperStruct::IsInitialized() const {
  return true;
}

void MySuperStruct::InternalSwap(MySuperStruct* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.superstring_, lhs_arena,
      &other->_impl_.superstring_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MySuperStruct, _impl_.superfloat_)
      + sizeof(MySuperStruct::_impl_.superfloat_)
      - PROTOBUF_FIELD_OFFSET(MySuperStruct, _impl_.superint_)>(
          reinterpret_cast<char*>(&_impl_.superint_),
          reinterpret_cast<char*>(&other->_impl_.superint_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MySuperStruct::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_pc2d_2eproto_getter, &descriptor_table_pc2d_2eproto_once,
      file_level_metadata_pc2d_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::MySuperStruct*
Arena::CreateMaybeMessage< ::MySuperStruct >(Arena* arena) {
  return Arena::CreateMessageInternal< ::MySuperStruct >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
